// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons-group': string;
  'buttons-group__item': string;
  'buttons-group__item_active': string;
  'color-green': string;
  'color-grey': string;
  'color-orange': string;
  'color-pink': string;
  'color-red': string;
  'color-violet': string;
  'color-white': string;
  'color-yellow': string;
  'danger': string;
  'dashboard-statistic': string;
  'modal-background': string;
  'primary': string;
  'primary-background': string;
  'projects': string;
  'projects-wrapper': string;
  'projects__button': string;
  'projects__button_scroll': string;
  'projects__data': string;
  'projects__types': string;
  'projects__types-add': string;
  'secondary': string;
  'secondary-light': string;
  'secondary-light-2': string;
  'sidebar-link': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-primary-light-2': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
