// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active-row': string;
  'table': string;
  'table__tbody-tr': string;
  'table__td': string;
  'table__th': string;
  'table__thead-tr': string;
}
export const cssExports: CssExports;
export default cssExports;
