// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__action-wrapper': string;
  'card__button': string;
  'card__button_active': string;
  'card__date': string;
  'card__footer': string;
  'card__footer-button': string;
  'card__footer-button-wrapper': string;
  'card__footer-button_active': string;
  'card__header': string;
  'card__title': string;
  'card__total': string;
  'card__total-item': string;
  'card__total-text': string;
  'card__total-title': string;
  'card__totals': string;
  'card__totals-wrapper': string;
  'danger': string;
  'primary': string;
  'primary-background': string;
  'secondary': string;
  'secondary-light': string;
  'sidebar-link': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-primary-light-2': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
