// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'modal': string;
  'modal-content': string;
  'modal-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
