// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logo-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
