// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pure-material-button-contained': string;
}
export const cssExports: CssExports;
export default cssExports;
