// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'estimate': string;
  'estimate-add': string;
  'estimate-page': string;
  'estimate-pin': string;
  'estimate-pin_active': string;
  'estimate-time': string;
  'estimate-title': string;
  'estimate-wrapper': string;
  'estimate__link': string;
  'estimate__trash': string;
}
export const cssExports: CssExports;
export default cssExports;
