// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'danger': string;
  'estimate': string;
  'estimate-add': string;
  'estimate-page': string;
  'estimate-pin': string;
  'estimate-pin_active': string;
  'estimate-time': string;
  'estimate-title': string;
  'estimate-wrapper': string;
  'estimate__link': string;
  'estimate__trash': string;
  'primary': string;
  'primary-background': string;
  'secondary': string;
  'sidebar-link': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
