// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'estimate': string;
  'estimate-add': string;
  'estimate-page': string;
  'estimate-title': string;
  'estimate-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
