// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbar__avatar': string;
  'navbar__avatar-setting': string;
  'navbar__avatar-wrapper': string;
  'navbar__user-email': string;
  'navbar__user-info': string;
  'navbar__user-name': string;
  'navbar__user-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
