// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'highlight': string;
  'highlight_2': string;
}
export const cssExports: CssExports;
export default cssExports;
