// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu__icon': string;
  'menu__item': string;
  'menu__link': string;
}
export const cssExports: CssExports;
export default cssExports;
