// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-green': string;
  'color-grey': string;
  'color-orange': string;
  'color-pink': string;
  'color-red': string;
  'color-violet': string;
  'color-white': string;
  'color-yellow': string;
  'danger': string;
  'dashboard-statistic': string;
  'primary': string;
  'primary-background': string;
  'secondary': string;
  'secondary-light': string;
  'sidebar': string;
  'sidebar-link': string;
  'sidebar__closed': string;
  'sidebar__link_active': string;
  'sidebar__open': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-primary-light-2': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
