// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__body': string;
  'card__footer': string;
  'card__header': string;
  'danger': string;
  'primary': string;
  'primary-background': string;
  'secondary': string;
  'secondary-light': string;
  'sidebar-link': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-primary-light-2': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
