// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'app_open': string;
  'color-green': string;
  'color-grey': string;
  'color-orange': string;
  'color-pink': string;
  'color-red': string;
  'color-violet': string;
  'color-white': string;
  'color-yellow': string;
  'danger': string;
  'dashboard-statistic': string;
  'modal-background': string;
  'primary': string;
  'primary-background': string;
  'secondary': string;
  'secondary-light': string;
  'secondary-light-2': string;
  'sidebar-link': string;
  'success': string;
  'text-dark-grey': string;
  'text-light': string;
  'text-light-grey': string;
  'text-primary': string;
  'text-primary-light': string;
  'text-primary-light-2': string;
  'text-primary-light-3': string;
  'text-secondary': string;
  'text-secondary-light': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
