// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppCssNamespace {
  export interface IAppCss {
    red: string;
  }
}

declare const AppCssModule: AppCssNamespace.IAppCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppCssNamespace.IAppCss;
};

export = AppCssModule;
