// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'floater': string;
  'form-control': string;
  'form-control-wrapper': string;
  'touched': string;
}
export const cssExports: CssExports;
export default cssExports;
